v = input('Digite algo: ')
print(f'\nDigitado......: {v}')
print(f'Tipo..........: {type(v)}')
print(f'Alpha.........: {v.isalpha()}')
print(f'Numeric.......: {v.isnumeric()}')
print(f'Alpha numeric.: {v.isalnum()}')
print(f'Digit.........: {v.isdigit()}')
print(f'Só minúsculo..: {v.islower()}')
print(f'Só maiúsculo..: {v.isupper()}')
print(f'Printável.....: {v.isprintable()}')
